const constants = {
    CLEAR_BASKET_ALERT: "CLEAR_BASKET_ALERT",
    REMOVE_ITEM_FROM_BASKET: "REMOVE_ITEM_FROM_BASKET",
    TOGGLE_BASKET: "TOGGLE_BASKET",
    CHANGE_QUANTITY_OF_PRODUCT: "CHANGE_QUANTITY_OF_PRODUCT",
    ADD_TO_BASKET: "ADD_TO_BASKET",
    SET_PRODUCTS: "SET_PRODUCTS"
}

export {constants}
